from time import perf_counter, sleep

import robot
from rightSpeedModifier import rightSpeedmodifier

arlo = robot.Robot()

print(arlo.go_diff(0, 44, 1, 0))
sleep(2)
print(arlo.stop())
sleep(4)
print(arlo.go_diff(0, 44, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 52, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 60, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 72, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 80, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 88, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 96, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 104, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 112, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(0, 120, 1, 0))
sleep(2)
print(arlo.stop())
sleep(2)
