from time import perf_counter, sleep

import robot

arlo = robot.Robot()

print(arlo.go_diff(44, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(4)
print(arlo.go_diff(44, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(52, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(60, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(72, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(80, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(88, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(96, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(104, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(112, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
print(arlo.go_diff(120, 0, 0, 0))
sleep(2)
print(arlo.stop())
sleep(2)
